import type { User, Task, Repository, PullRequest, Conversation, DocPage, Integration, Comment } from "@/types";

export const currentUser: User = {
  id: "u1",
  name: "Alex Chen",
  email: "alex@nexusai.dev",
  avatar: "",
  role: "Senior Engineer",
};

export const teamMembers: User[] = [
  currentUser,
  { id: "u2", name: "Sarah Kim", email: "sarah@nexusai.dev", avatar: "", role: "Tech Lead" },
  { id: "u3", name: "Marcus Johnson", email: "marcus@nexusai.dev", avatar: "", role: "Full Stack Dev" },
  { id: "u4", name: "Emily Park", email: "emily@nexusai.dev", avatar: "", role: "DevOps Engineer" },
  { id: "u5", name: "David Liu", email: "david@nexusai.dev", avatar: "", role: "Frontend Dev" },
];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Implement user authentication flow",
    description: "Build a complete authentication system with login, register, and password recovery using NextAuth.js.",
    status: "in-progress",
    priority: "high",
    assignee: teamMembers[0],
    labels: ["backend", "auth"],
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-01-12T14:30:00Z",
    estimatedHours: 16,
    aiAnalysis: {
      summary: "Authentication flow requires implementing NextAuth.js with GitHub and Google OAuth providers, plus email/password fallback.",
      implementationPlan: [
        "Set up NextAuth.js configuration with providers",
        "Create login and register pages with form validation",
        "Implement session management and middleware",
        "Add password recovery flow with email verification",
        "Write integration tests for auth flows",
      ],
      complexity: "high",
      suggestedFiles: [
        "app/api/auth/[...nextauth]/route.ts",
        "app/(auth)/login/page.tsx",
        "app/(auth)/register/page.tsx",
        "lib/auth.ts",
        "middleware.ts",
      ],
      risks: [
        "Session token handling across different environments",
        "OAuth provider rate limits during testing",
        "CSRF protection implementation",
      ],
    },
  },
  {
    id: "t2",
    title: "Design system color token update",
    description: "Update the design system to support both light and dark mode with indigo/violet primary colors.",
    status: "done",
    priority: "medium",
    assignee: teamMembers[4],
    labels: ["design", "frontend"],
    createdAt: "2025-01-08T09:00:00Z",
    updatedAt: "2025-01-11T16:00:00Z",
    estimatedHours: 8,
  },
  {
    id: "t3",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing, linting, and deployment to Vercel.",
    status: "todo",
    priority: "high",
    assignee: teamMembers[3],
    labels: ["devops", "ci/cd"],
    createdAt: "2025-01-12T11:00:00Z",
    updatedAt: "2025-01-12T11:00:00Z",
    estimatedHours: 12,
  },
  {
    id: "t4",
    title: "Build Kanban drag-and-drop",
    description: "Implement drag-and-drop functionality for the Kanban board using dnd-kit.",
    status: "review",
    priority: "medium",
    assignee: teamMembers[2],
    labels: ["frontend", "ux"],
    createdAt: "2025-01-09T08:00:00Z",
    updatedAt: "2025-01-13T10:00:00Z",
    estimatedHours: 10,
  },
  {
    id: "t5",
    title: "API rate limiting middleware",
    description: "Implement rate limiting for all API endpoints using Redis.",
    status: "backlog",
    priority: "low",
    labels: ["backend", "security"],
    createdAt: "2025-01-13T09:00:00Z",
    updatedAt: "2025-01-13T09:00:00Z",
    estimatedHours: 6,
  },
  {
    id: "t6",
    title: "AI code review integration",
    description: "Integrate AI-powered code review suggestions into the pull request workflow.",
    status: "in-progress",
    priority: "urgent",
    assignee: teamMembers[1],
    labels: ["ai", "backend"],
    createdAt: "2025-01-11T14:00:00Z",
    updatedAt: "2025-01-13T16:00:00Z",
    estimatedHours: 20,
  },
  {
    id: "t7",
    title: "Performance monitoring dashboard",
    description: "Create a real-time performance monitoring dashboard with Core Web Vitals tracking.",
    status: "todo",
    priority: "medium",
    assignee: teamMembers[0],
    labels: ["frontend", "analytics"],
    createdAt: "2025-01-13T12:00:00Z",
    updatedAt: "2025-01-13T12:00:00Z",
    estimatedHours: 14,
  },
  {
    id: "t8",
    title: "Database migration scripts",
    description: "Write migration scripts for the new user preferences schema.",
    status: "done",
    priority: "low",
    assignee: teamMembers[3],
    labels: ["backend", "database"],
    createdAt: "2025-01-07T10:00:00Z",
    updatedAt: "2025-01-09T15:00:00Z",
    estimatedHours: 4,
  },
];

export const repositories: Repository[] = [
  {
    id: "r1",
    name: "nexus-ai-platform",
    description: "Main application repository for the Nexus AI developer workspace",
    language: "TypeScript",
    stars: 234,
    forks: 45,
    lastUpdated: "2025-01-13T16:00:00Z",
    files: [
      {
        name: "app",
        type: "folder",
        children: [
          { name: "layout.tsx", type: "file", size: "1.2 KB" },
          { name: "page.tsx", type: "file", size: "3.4 KB" },
          {
            name: "(dashboard)",
            type: "folder",
            children: [
              { name: "page.tsx", type: "file", size: "5.1 KB" },
              { name: "chat/page.tsx", type: "file", size: "8.2 KB" },
              { name: "tasks/page.tsx", type: "file", size: "6.7 KB" },
            ],
          },
        ],
      },
      {
        name: "components",
        type: "folder",
        children: [
          { name: "ui", type: "folder", children: [] },
          { name: "dashboard", type: "folder", children: [] },
          { name: "chat", type: "folder", children: [] },
        ],
      },
      { name: "package.json", type: "file", size: "1.1 KB" },
      { name: "tsconfig.json", type: "file", size: "0.8 KB" },
    ],
  },
  {
    id: "r2",
    name: "ai-engine",
    description: "Core AI processing engine with LLM integrations",
    language: "Python",
    stars: 189,
    forks: 32,
    lastUpdated: "2025-01-12T10:00:00Z",
    files: [],
  },
  {
    id: "r3",
    name: "nexus-design-system",
    description: "Shared design system and component library",
    language: "TypeScript",
    stars: 156,
    forks: 28,
    lastUpdated: "2025-01-11T14:00:00Z",
    files: [],
  },
  {
    id: "r4",
    name: "nexus-docs",
    description: "Internal documentation and API references",
    language: "MDX",
    stars: 78,
    forks: 12,
    lastUpdated: "2025-01-10T09:00:00Z",
    files: [],
  },
];

export const pullRequests: PullRequest[] = [
  {
    id: "pr1",
    title: "feat: Add AI chat streaming responses",
    description: "Implements real-time streaming for AI chat responses using Server-Sent Events. Includes markdown rendering and syntax highlighting.",
    status: "open",
    author: teamMembers[0],
    branch: "feat/ai-chat-streaming",
    targetBranch: "main",
    filesChanged: 12,
    additions: 847,
    deletions: 23,
    createdAt: "2025-01-13T10:00:00Z",
    reviewStatus: "pending",
  },
  {
    id: "pr2",
    title: "fix: Resolve dark mode toggle flicker",
    description: "Fixes the flash of incorrect theme on page load by implementing proper SSR-safe theme detection.",
    status: "merged",
    author: teamMembers[4],
    branch: "fix/dark-mode-flicker",
    targetBranch: "main",
    filesChanged: 4,
    additions: 89,
    deletions: 34,
    createdAt: "2025-01-12T15:00:00Z",
    reviewStatus: "approved",
  },
  {
    id: "pr3",
    title: "feat: Kanban board drag-and-drop",
    description: "Adds drag-and-drop support for moving tasks between columns on the Kanban board.",
    status: "open",
    author: teamMembers[2],
    branch: "feat/kanban-dnd",
    targetBranch: "main",
    filesChanged: 8,
    additions: 456,
    deletions: 12,
    createdAt: "2025-01-13T08:00:00Z",
    reviewStatus: "changes-requested",
  },
  {
    id: "pr4",
    title: "chore: Update dependencies",
    description: "Bumps all dependencies to latest stable versions. Includes migration notes.",
    status: "closed",
    author: teamMembers[3],
    branch: "chore/deps-update",
    targetBranch: "main",
    filesChanged: 2,
    additions: 1200,
    deletions: 1180,
    createdAt: "2025-01-11T09:00:00Z",
    reviewStatus: "approved",
  },
];

export const conversations: Conversation[] = [
  {
    id: "c1",
    title: "How to implement auth with NextAuth.js",
    messages: [
      { id: "m1", role: "user", content: "How should I implement authentication in my Next.js app?", timestamp: "2025-01-13T10:00:00Z" },
      { id: "m2", role: "assistant", content: "I recommend using NextAuth.js for authentication in Next.js applications. Here's a step-by-step approach:\n\n1. **Install NextAuth.js**\n```bash\nnpm install next-auth\n```\n\n2. **Create the auth configuration**\n```typescript\n// app/api/auth/[...nextauth]/route.ts\nimport NextAuth from \"next-auth\"\nimport GitHubProvider from \"next-auth/providers/github\"\n\nconst handler = NextAuth({\n  providers: [\n    GitHubProvider({\n      clientId: process.env.GITHUB_ID!,\n      clientSecret: process.env.GITHUB_SECRET!,\n    }),\n  ],\n})\n\nexport { handler as GET, handler as POST }\n```\n\n3. **Add the session provider** to your root layout\n4. **Protect routes** with middleware\n\nThis approach gives you session management, CSRF protection, and OAuth providers out of the box.", timestamp: "2025-01-13T10:01:00Z" },
    ],
    createdAt: "2025-01-13T10:00:00Z",
    updatedAt: "2025-01-13T10:01:00Z",
  },
  {
    id: "c2",
    title: "Optimize React rendering performance",
    messages: [],
    createdAt: "2025-01-12T14:00:00Z",
    updatedAt: "2025-01-12T14:00:00Z",
  },
  {
    id: "c3",
    title: "Database schema design for tasks",
    messages: [],
    createdAt: "2025-01-11T09:00:00Z",
    updatedAt: "2025-01-11T09:00:00Z",
  },
];

export const docPages: DocPage[] = [
  {
    id: "d1",
    title: "Getting Started",
    content: "# Getting Started\n\nWelcome to Nexus AI documentation. This guide will help you set up and configure your development environment.\n\n## Prerequisites\n\n- Node.js 18+\n- npm or yarn\n- Git\n\n## Installation\n\n```bash\nnpx create-nexus-app my-project\ncd my-project\nnpm run dev\n```\n\n## Configuration\n\nCreate a `.env.local` file with your API keys:\n\n```\nNEXT_PUBLIC_API_URL=https://api.nexusai.dev\nOPENAI_API_KEY=your-key-here\n```",
    icon: "🚀",
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-01-13T16:00:00Z",
  },
  {
    id: "d2",
    title: "API Reference",
    content: "# API Reference\n\n## Authentication\n\nAll API requests require a Bearer token.\n\n## Endpoints\n\n### GET /api/tasks\nReturns a list of tasks.\n\n### POST /api/tasks\nCreates a new task.\n\n### PUT /api/tasks/:id\nUpdates a task.",
    icon: "📡",
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-01-12T14:00:00Z",
  },
  {
    id: "d3",
    title: "Deployment Guide",
    content: "# Deployment Guide\n\n## Vercel Deployment\n\n1. Push to GitHub\n2. Import in Vercel\n3. Configure environment variables\n4. Deploy",
    icon: "🚢",
    createdAt: "2025-01-11T10:00:00Z",
    updatedAt: "2025-01-11T10:00:00Z",
  },
];

export const integrations: Integration[] = [
  { id: "i1", name: "GitHub", description: "Connect repositories and manage pull requests", icon: "github", connected: true, category: "Version Control" },
  { id: "i2", name: "GitLab", description: "Sync with GitLab repositories and pipelines", icon: "gitlab", connected: false, category: "Version Control" },
  { id: "i3", name: "Jira", description: "Import and sync issues from Jira boards", icon: "jira", connected: true, category: "Project Management" },
  { id: "i4", name: "Slack", description: "Get notifications and updates in Slack channels", icon: "slack", connected: false, category: "Communication" },
  { id: "i5", name: "Linear", description: "Sync issues and project data with Linear", icon: "linear", connected: false, category: "Project Management" },
  { id: "i6", name: "Vercel", description: "Deploy previews and production deployments", icon: "vercel", connected: true, category: "Deployment" },
];

export const comments: Comment[] = [
  { id: "cm1", author: teamMembers[1], content: "Looks great! Just a few suggestions on the error handling.", createdAt: "2025-01-13T11:00:00Z" },
  { id: "cm2", author: teamMembers[0], content: "Good point, I've updated the error boundaries.", createdAt: "2025-01-13T12:00:00Z" },
  { id: "cm3", author: teamMembers[2], content: "Should we add retry logic for failed API calls?", createdAt: "2025-01-13T13:00:00Z" },
];
